# Generated by Django 5.2.4 on 2025-08-08 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_alter_book_user_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_content',
            field=models.TextField(default=" \n    Here's a detailed explanation of the Django Authentication System, covering all the points you've listed:\n\n    🔐 Django Authentication System\n    Django comes with a built-in authentication system that handles:\n\n    User registration and login\n\n    Password hashing and security\n\n    Permissions and groups\n\n    Custom user models\n\n    Lets explore each part in detail:\n\n    1. ✅ User Model & User Management\n    Django provides a built-in User model in django.contrib.auth.models.\n\n    Default fields:\n\n    username\n\n    password (stored hashed)\n\n    email\n\n    first_name, last_name\n\n    is_active, is_staff, is_superuser\n\n    last_login, date_joined\n"),
        ),
    ]
