# Generated by Django 5.2.4 on 2025-08-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_book_book_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookopenfrequency',
            name='book',
        ),
        migrations.AlterField(
            model_name='book',
            name='book_content',
            field=models.TextField(),
        ),
    ]
